"""Trust Receipt Service — Authoritative Certificate Retrieval and Provenance Validation.

Retrieves verified JSON Trust Receipts generated by the GeoFUSE pipeline,
preserving all cryptographic, radiometric, and structural provenance metadata.
"""

import json
from pathlib import Path
from typing import Any, Dict, Optional

from src.api.config import CACHE_API_DIR, DEMO_CACHE_DIR, OUTPUTS_DIR


class ReceiptService:
    """Manages lookup and retrieval of authoritative Trust Receipts."""

    def get_receipt(self, receipt_or_run_id: str) -> Optional[Dict[str, Any]]:
        """Find and load an authoritative Trust Receipt by receipt_id or run_id."""
        raw_id = receipt_or_run_id.strip()
        # Security: reject any path traversal or invalid characters
        if ".." in raw_id or "/" in raw_id or "\\" in raw_id:
            return None
        clean_id = Path(raw_id).name

        # 1. Direct path check in cache_api
        direct_file = CACHE_API_DIR / clean_id / "receipt.json"
        if direct_file.exists():
            with open(direct_file, "r", encoding="utf-8") as f:
                return json.load(f)

        # 2. Search all run folders in cache_api
        for run_dir in CACHE_API_DIR.iterdir():
            if run_dir.is_dir():
                r_file = run_dir / "receipt.json"
                if r_file.exists():
                    try:
                        with open(r_file, "r", encoding="utf-8") as f:
                            data = json.load(f)
                            if data.get("receipt_id") == clean_id:
                                return data
                    except Exception:
                        continue

        # 3. Search outputs/receipts/
        receipts_dir = OUTPUTS_DIR / "receipts"
        if receipts_dir.exists():
            for rf in receipts_dir.glob("*.json"):
                try:
                    with open(rf, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        if data.get("receipt_id") == clean_id or rf.stem == clean_id:
                            return data
                except Exception:
                    continue

        # 4. Search outputs/demo_cache/
        if DEMO_CACHE_DIR.exists():
            for df in DEMO_CACHE_DIR.glob("*receipt*.json"):
                try:
                    with open(df, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        if data.get("receipt_id") == clean_id or df.stem == clean_id:
                            return data
                except Exception:
                    continue

        return None


# Singleton instance
receipt_service = ReceiptService()
